Gitignore artifacts. Add DepositContract and modify the DepositFactoryContract in order to create multi instances of DepositContract by the clone pattern
Sprynt-io/Sprynt-mint-contracts pull request #2
Opened 2023-04-28 02:40 UTC by NguyetPhamFuix

closes #109, #141, #142, #143

2023-04-28 04:34 UTC, ngmitam commented
Please write unit tests whenever you can, thanks

2023-04-30 09:39 UTC, NguyetPhamFuix commented
> Please write unit tests whenever you can, thanks

I have updated the unit tests to make sure the defined flow run well. Thank you very much.

2023-05-04 06:24 UTC, ngmitam requested changes

2023-05-04 06:24 UTC, ngmitam commented on contracts/childs/DepositContract.sol
> +    address public tokenAddress;
should have minted to keep track number of minted token

2023-05-04 06:24 UTC, ngmitam commented on contracts/childs/DepositContract.sol
> +        DepositFactoryContract(_factoryContractAddress).depositTokenByClient{
Please check totalSupply, mintQuantity, dstChainId, selleraddress, tokenAddress, ...

2023-05-04 06:24 UTC, ngmitam commented on contracts/childs/DepositContract.sol
> +    function changeMintPrice(uint256 mintPrice_) public onlyPermissioned {
For each function can call by factoryContract please create a function for factoryContract, these function sould only call by configure role

2023-05-07 13:02 UTC, NguyetPhamFuix commented on contracts/childs/DepositContract.sol
> +        DepositFactoryContract(_factoryContractAddress).depositTokenByClient{
These information are included in the DepositItem struct.

2023-05-07 13:06 UTC, NguyetPhamFuix commented on contracts/childs/DepositContract.sol
> +    function changeMintPrice(uint256 mintPrice_) public onlyPermissioned {
Could you explain this more. I have create the "onlyPermissioned" modifier to set that these functions can only be called by seller and factoryContract. So how can I modify this as your requirement.
![image](https://user-images.githubusercontent.com/131739278/236679326-48b294d3-bf96-46d3-8a9c-e3dda5448df7.png)

2023-05-07 13:22 UTC, ngmitam commented on contracts/childs/DepositContract.sol
> +    function changeMintPrice(uint256 mintPrice_) public onlyPermissioned {
These function can be called by factoryContract, but now factoryContract don't have functions to call them. So please create functions on factoryContract

2023-05-07 13:25 UTC, ngmitam commented on contracts/childs/DepositContract.sol
> +        DepositFactoryContract(_factoryContractAddress).depositTokenByClient{
Yes, but check these info with contract's config.

2023-05-07 13:42 UTC, NguyetPhamFuix commented on contracts/childs/DepositContract.sol
> +    function changeMintPrice(uint256 mintPrice_) public onlyPermissioned {
Ah I see. Thank you. I will fix it now

2023-05-07 13:44 UTC, ngmitam commented
Should also keep track the minted token on receiver contract and generate token id automatically, dont allow user to set tokenId. We have multi deposit chains.

2023-05-07 14:13 UTC, ngmitam commented
We use ERC1155 for NFT, so 1 tokenId only supply 1.

2023-05-08 03:03 UTC, ngmitam commented on contracts/parents/DepositFactoryContract.sol
> +    function setupDepositRole(
Should also have revokeRole

2023-05-08 09:25 UTC, ngmitam commented on contracts/childs/ERC1155.sol
> +    mapping(address => uint256) private _mintedTokens;
It is just a number, no need to map with address

2023-05-08 09:48 UTC, ngmitam commented on contracts/parents/ReceiveFactoryContract.sol
> +    uint256 private _mintedTokens;
Keep track of the minted on the NFT contract, not here

2023-05-08 09:52 UTC, ngmitam commented on contracts/parents/ReceiveFactoryContract.sol
> +        uint256[] memory ids = new uint256[](mintQuantity);
Override the minBatchToken of NFT contract, don't implement logic here

2023-05-15 04:29 UTC, ngmitam commented on contracts/parents/DepositFactoryContract.sol
> +            IERC20(_acceptToken).safeTransferFrom(
Should allow seller to set acceptToken on their depositContract and use it

2023-05-15 09:36 UTC, ngmitam commented on contracts/parents/DepositFactoryContract.sol
> +            address sellerAddress,
It should be a map
mapping(address => address) public sellerToDepositContract;

2023-05-15 10:30 UTC, ngmitam approved these changes

2023-05-15 10:30 UTC, ngmitam commented on contracts/childs/DepositContract.sol
> +    ) public payable {
check mintPrice
if whiteList use whiteListMintPrice

2023-05-15 10:33 UTC, ngmitam commented on contracts/parents/DepositFactoryContract.sol
> +            address sellerAddress,
@NguyetPhamFuix

2023-05-15 10:33 UTC, ngmitam commented on contracts/parents/DepositFactoryContract.sol
> +            IERC20(_acceptToken).safeTransferFrom(
@NguyetPhamFuix

2023-05-15 10:34 UTC, ngmitam commented on contracts/childs/DepositContract.sol
> +    ) public payable {
@NguyetPhamFuix

2023-05-26 03:03 UTC, ngmitam commented on contracts/parents/ReceiveFactoryContract.sol
> +    function _nonblockingLzReceive(
We will no longer use LayerZero to mint, instead, we call directly by our account.

2023-05-26 08:21 UTC, ngmitam commented on contracts/childs/DepositContract.sol
> +    function mint(
We will no longer use LayerZero

2023-05-26 08:21 UTC, ngmitam commented on contracts/parents/DepositFactoryContract.sol
> +    function depositTokenByClient(
We will no longer user LayerZero

2023-05-30 04:23 UTC, ngmitam requested changes

2023-05-30 04:23 UTC, ngmitam commented on contracts/parents/DepositFactoryContract.sol
> +        SimplePay simplePayContract = new SimplePay(
Use clone factory

2023-05-30 04:23 UTC, ngmitam commented on contracts/parents/DepositFactoryContract.sol
> +    //             address masterDepositContractAddress = address(
always use clone factory, don't use new

2023-05-30 04:23 UTC, ngmitam commented on contracts/parents/ReceiveFactoryContract.sol
> +        ERC1155Contract newNftContract = new ERC1155Contract(
Alway use clone factory

2023-05-30 04:23 UTC, ngmitam commented on contracts/childs/ERC1155.sol
> +    ) external onlyRole(FACTORY_CONTRACT_ROLE) nonReentrant {
Should allow our account to mint Token (MINT ROLE or ...)

2023-05-30 04:23 UTC, ngmitam commented on contracts/childs/ERC1155.sol
> +    ) external onlyRole(FACTORY_CONTRACT_ROLE) nonReentrant {
Same as mintToken

2023-05-30 09:31 UTC, ngmitam commented on contracts/parents/DepositFactoryContract.sol
> +                    new DepositContract(
Don't use new, it makes the code size increase

2023-05-30 09:49 UTC, ngmitam commented
Resolve conflicts

2023-05-31 03:47 UTC, NguyetPhamFuix commented on contracts/parents/DepositFactoryContract.sol
> +                    new DepositContract(
How should we do if we haven't had a master contract to create clone yet?

2023-05-31 07:17 UTC, ngmitam commented on contracts/parents/DepositFactoryContract.sol
> +                    new DepositContract(
Deploy master contract then set on the contract

2023-05-31 10:16 UTC, ngmitam commented
Please update tasks script and deploy to test nets

2023-06-01 06:44 UTC, ngmitam commented
We still need mint function on depositContract, but don't send to layerZero. Please change it.

2023-06-04 12:33 UTC, ngmitam commented
Continue other tasks with the master branch. These tasks are completed.

2023-06-04 12:33 UTC, closed without merging